/*
 * generated by Xtext 2.12.0
 */
package linit


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class LinitStandaloneSetup extends LinitStandaloneSetupGenerated {

	def static void doSetup() {
		new LinitStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
