/**
 * generated by Xtext 2.12.0
 */
package linit.linit;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>ciclo</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see linit.linit.LinitPackage#getciclo()
 * @model
 * @generated
 */
public interface ciclo extends EObject
{
} // ciclo
