/**
 * generated by Xtext 2.12.0
 */
package linit.linit;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>instrucciones</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link linit.linit.instrucciones#getI <em>I</em>}</li>
 *   <li>{@link linit.linit.instrucciones#getC <em>C</em>}</li>
 *   <li>{@link linit.linit.instrucciones#getF <em>F</em>}</li>
 * </ul>
 *
 * @see linit.linit.LinitPackage#getinstrucciones()
 * @model
 * @generated
 */
public interface instrucciones extends ciclo
{
  /**
   * Returns the value of the '<em><b>I</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>I</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>I</em>' containment reference.
   * @see #setI(instrucciones)
   * @see linit.linit.LinitPackage#getinstrucciones_I()
   * @model containment="true"
   * @generated
   */
  instrucciones getI();

  /**
   * Sets the value of the '{@link linit.linit.instrucciones#getI <em>I</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>I</em>' containment reference.
   * @see #getI()
   * @generated
   */
  void setI(instrucciones value);

  /**
   * Returns the value of the '<em><b>C</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>C</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>C</em>' containment reference.
   * @see #setC(condicional)
   * @see linit.linit.LinitPackage#getinstrucciones_C()
   * @model containment="true"
   * @generated
   */
  condicional getC();

  /**
   * Sets the value of the '{@link linit.linit.instrucciones#getC <em>C</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>C</em>' containment reference.
   * @see #getC()
   * @generated
   */
  void setC(condicional value);

  /**
   * Returns the value of the '<em><b>F</b></em>' containment reference list.
   * The list contents are of type {@link linit.linit.ciclo}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>F</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>F</em>' containment reference list.
   * @see linit.linit.LinitPackage#getinstrucciones_F()
   * @model containment="true"
   * @generated
   */
  EList<ciclo> getF();

} // instrucciones
