/**
 * generated by Xtext 2.12.0
 */
package linit.linit;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see linit.linit.LinitPackage
 * @generated
 */
public interface LinitFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LinitFactory eINSTANCE = linit.linit.impl.LinitFactoryImpl.init();

  /**
   * Returns a new object of class '<em>programa</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>programa</em>'.
   * @generated
   */
  programa createprograma();

  /**
   * Returns a new object of class '<em>declaraciones</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>declaraciones</em>'.
   * @generated
   */
  declaraciones createdeclaraciones();

  /**
   * Returns a new object of class '<em>instrucciones</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>instrucciones</em>'.
   * @generated
   */
  instrucciones createinstrucciones();

  /**
   * Returns a new object of class '<em>condicional</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>condicional</em>'.
   * @generated
   */
  condicional createcondicional();

  /**
   * Returns a new object of class '<em>ciclo</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ciclo</em>'.
   * @generated
   */
  ciclo createciclo();

  /**
   * Returns a new object of class '<em>lista Condicional</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>lista Condicional</em>'.
   * @generated
   */
  listaCondicional createlistaCondicional();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  LinitPackage getLinitPackage();

} //LinitFactory
