/**
 * generated by Xtext 2.12.0
 */
package linit.linit;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see linit.linit.LinitFactory
 * @model kind="package"
 * @generated
 */
public interface LinitPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "linit";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.Linit.linit";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "linit";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  LinitPackage eINSTANCE = linit.linit.impl.LinitPackageImpl.init();

  /**
   * The meta object id for the '{@link linit.linit.impl.programaImpl <em>programa</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see linit.linit.impl.programaImpl
   * @see linit.linit.impl.LinitPackageImpl#getprograma()
   * @generated
   */
  int PROGRAMA = 0;

  /**
   * The feature id for the '<em><b>D</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA__D = 0;

  /**
   * The feature id for the '<em><b>I</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA__I = 1;

  /**
   * The number of structural features of the '<em>programa</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PROGRAMA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link linit.linit.impl.declaracionesImpl <em>declaraciones</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see linit.linit.impl.declaracionesImpl
   * @see linit.linit.impl.LinitPackageImpl#getdeclaraciones()
   * @generated
   */
  int DECLARACIONES = 1;

  /**
   * The feature id for the '<em><b>I</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARACIONES__I = 0;

  /**
   * The feature id for the '<em><b>D</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARACIONES__D = 1;

  /**
   * The number of structural features of the '<em>declaraciones</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DECLARACIONES_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link linit.linit.impl.cicloImpl <em>ciclo</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see linit.linit.impl.cicloImpl
   * @see linit.linit.impl.LinitPackageImpl#getciclo()
   * @generated
   */
  int CICLO = 4;

  /**
   * The number of structural features of the '<em>ciclo</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CICLO_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link linit.linit.impl.instruccionesImpl <em>instrucciones</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see linit.linit.impl.instruccionesImpl
   * @see linit.linit.impl.LinitPackageImpl#getinstrucciones()
   * @generated
   */
  int INSTRUCCIONES = 2;

  /**
   * The feature id for the '<em><b>I</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCCIONES__I = CICLO_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>C</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCCIONES__C = CICLO_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>F</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCCIONES__F = CICLO_FEATURE_COUNT + 2;

  /**
   * The number of structural features of the '<em>instrucciones</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INSTRUCCIONES_FEATURE_COUNT = CICLO_FEATURE_COUNT + 3;

  /**
   * The meta object id for the '{@link linit.linit.impl.condicionalImpl <em>condicional</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see linit.linit.impl.condicionalImpl
   * @see linit.linit.impl.LinitPackageImpl#getcondicional()
   * @generated
   */
  int CONDICIONAL = 3;

  /**
   * The feature id for the '<em><b>I</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDICIONAL__I = 0;

  /**
   * The feature id for the '<em><b>L</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDICIONAL__L = 1;

  /**
   * The number of structural features of the '<em>condicional</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CONDICIONAL_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link linit.linit.impl.listaCondicionalImpl <em>lista Condicional</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see linit.linit.impl.listaCondicionalImpl
   * @see linit.linit.impl.LinitPackageImpl#getlistaCondicional()
   * @generated
   */
  int LISTA_CONDICIONAL = 5;

  /**
   * The feature id for the '<em><b>I</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTA_CONDICIONAL__I = 0;

  /**
   * The feature id for the '<em><b>L</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTA_CONDICIONAL__L = 1;

  /**
   * The number of structural features of the '<em>lista Condicional</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LISTA_CONDICIONAL_FEATURE_COUNT = 2;


  /**
   * Returns the meta object for class '{@link linit.linit.programa <em>programa</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>programa</em>'.
   * @see linit.linit.programa
   * @generated
   */
  EClass getprograma();

  /**
   * Returns the meta object for the containment reference '{@link linit.linit.programa#getD <em>D</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>D</em>'.
   * @see linit.linit.programa#getD()
   * @see #getprograma()
   * @generated
   */
  EReference getprograma_D();

  /**
   * Returns the meta object for the containment reference '{@link linit.linit.programa#getI <em>I</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>I</em>'.
   * @see linit.linit.programa#getI()
   * @see #getprograma()
   * @generated
   */
  EReference getprograma_I();

  /**
   * Returns the meta object for class '{@link linit.linit.declaraciones <em>declaraciones</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>declaraciones</em>'.
   * @see linit.linit.declaraciones
   * @generated
   */
  EClass getdeclaraciones();

  /**
   * Returns the meta object for the containment reference '{@link linit.linit.declaraciones#getI <em>I</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>I</em>'.
   * @see linit.linit.declaraciones#getI()
   * @see #getdeclaraciones()
   * @generated
   */
  EReference getdeclaraciones_I();

  /**
   * Returns the meta object for the containment reference '{@link linit.linit.declaraciones#getD <em>D</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>D</em>'.
   * @see linit.linit.declaraciones#getD()
   * @see #getdeclaraciones()
   * @generated
   */
  EReference getdeclaraciones_D();

  /**
   * Returns the meta object for class '{@link linit.linit.instrucciones <em>instrucciones</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>instrucciones</em>'.
   * @see linit.linit.instrucciones
   * @generated
   */
  EClass getinstrucciones();

  /**
   * Returns the meta object for the containment reference '{@link linit.linit.instrucciones#getI <em>I</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>I</em>'.
   * @see linit.linit.instrucciones#getI()
   * @see #getinstrucciones()
   * @generated
   */
  EReference getinstrucciones_I();

  /**
   * Returns the meta object for the containment reference '{@link linit.linit.instrucciones#getC <em>C</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>C</em>'.
   * @see linit.linit.instrucciones#getC()
   * @see #getinstrucciones()
   * @generated
   */
  EReference getinstrucciones_C();

  /**
   * Returns the meta object for the containment reference list '{@link linit.linit.instrucciones#getF <em>F</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>F</em>'.
   * @see linit.linit.instrucciones#getF()
   * @see #getinstrucciones()
   * @generated
   */
  EReference getinstrucciones_F();

  /**
   * Returns the meta object for class '{@link linit.linit.condicional <em>condicional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>condicional</em>'.
   * @see linit.linit.condicional
   * @generated
   */
  EClass getcondicional();

  /**
   * Returns the meta object for the containment reference '{@link linit.linit.condicional#getI <em>I</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>I</em>'.
   * @see linit.linit.condicional#getI()
   * @see #getcondicional()
   * @generated
   */
  EReference getcondicional_I();

  /**
   * Returns the meta object for the containment reference '{@link linit.linit.condicional#getL <em>L</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>L</em>'.
   * @see linit.linit.condicional#getL()
   * @see #getcondicional()
   * @generated
   */
  EReference getcondicional_L();

  /**
   * Returns the meta object for class '{@link linit.linit.ciclo <em>ciclo</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ciclo</em>'.
   * @see linit.linit.ciclo
   * @generated
   */
  EClass getciclo();

  /**
   * Returns the meta object for class '{@link linit.linit.listaCondicional <em>lista Condicional</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>lista Condicional</em>'.
   * @see linit.linit.listaCondicional
   * @generated
   */
  EClass getlistaCondicional();

  /**
   * Returns the meta object for the containment reference '{@link linit.linit.listaCondicional#getI <em>I</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>I</em>'.
   * @see linit.linit.listaCondicional#getI()
   * @see #getlistaCondicional()
   * @generated
   */
  EReference getlistaCondicional_I();

  /**
   * Returns the meta object for the containment reference '{@link linit.linit.listaCondicional#getL <em>L</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>L</em>'.
   * @see linit.linit.listaCondicional#getL()
   * @see #getlistaCondicional()
   * @generated
   */
  EReference getlistaCondicional_L();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  LinitFactory getLinitFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link linit.linit.impl.programaImpl <em>programa</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see linit.linit.impl.programaImpl
     * @see linit.linit.impl.LinitPackageImpl#getprograma()
     * @generated
     */
    EClass PROGRAMA = eINSTANCE.getprograma();

    /**
     * The meta object literal for the '<em><b>D</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAMA__D = eINSTANCE.getprograma_D();

    /**
     * The meta object literal for the '<em><b>I</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference PROGRAMA__I = eINSTANCE.getprograma_I();

    /**
     * The meta object literal for the '{@link linit.linit.impl.declaracionesImpl <em>declaraciones</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see linit.linit.impl.declaracionesImpl
     * @see linit.linit.impl.LinitPackageImpl#getdeclaraciones()
     * @generated
     */
    EClass DECLARACIONES = eINSTANCE.getdeclaraciones();

    /**
     * The meta object literal for the '<em><b>I</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARACIONES__I = eINSTANCE.getdeclaraciones_I();

    /**
     * The meta object literal for the '<em><b>D</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DECLARACIONES__D = eINSTANCE.getdeclaraciones_D();

    /**
     * The meta object literal for the '{@link linit.linit.impl.instruccionesImpl <em>instrucciones</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see linit.linit.impl.instruccionesImpl
     * @see linit.linit.impl.LinitPackageImpl#getinstrucciones()
     * @generated
     */
    EClass INSTRUCCIONES = eINSTANCE.getinstrucciones();

    /**
     * The meta object literal for the '<em><b>I</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCCIONES__I = eINSTANCE.getinstrucciones_I();

    /**
     * The meta object literal for the '<em><b>C</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCCIONES__C = eINSTANCE.getinstrucciones_C();

    /**
     * The meta object literal for the '<em><b>F</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INSTRUCCIONES__F = eINSTANCE.getinstrucciones_F();

    /**
     * The meta object literal for the '{@link linit.linit.impl.condicionalImpl <em>condicional</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see linit.linit.impl.condicionalImpl
     * @see linit.linit.impl.LinitPackageImpl#getcondicional()
     * @generated
     */
    EClass CONDICIONAL = eINSTANCE.getcondicional();

    /**
     * The meta object literal for the '<em><b>I</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDICIONAL__I = eINSTANCE.getcondicional_I();

    /**
     * The meta object literal for the '<em><b>L</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference CONDICIONAL__L = eINSTANCE.getcondicional_L();

    /**
     * The meta object literal for the '{@link linit.linit.impl.cicloImpl <em>ciclo</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see linit.linit.impl.cicloImpl
     * @see linit.linit.impl.LinitPackageImpl#getciclo()
     * @generated
     */
    EClass CICLO = eINSTANCE.getciclo();

    /**
     * The meta object literal for the '{@link linit.linit.impl.listaCondicionalImpl <em>lista Condicional</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see linit.linit.impl.listaCondicionalImpl
     * @see linit.linit.impl.LinitPackageImpl#getlistaCondicional()
     * @generated
     */
    EClass LISTA_CONDICIONAL = eINSTANCE.getlistaCondicional();

    /**
     * The meta object literal for the '<em><b>I</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LISTA_CONDICIONAL__I = eINSTANCE.getlistaCondicional_I();

    /**
     * The meta object literal for the '<em><b>L</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference LISTA_CONDICIONAL__L = eINSTANCE.getlistaCondicional_L();

  }

} //LinitPackage
