/**
 * generated by Xtext 2.12.0
 */
package linit.linit;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>lista Condicional</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link linit.linit.listaCondicional#getI <em>I</em>}</li>
 *   <li>{@link linit.linit.listaCondicional#getL <em>L</em>}</li>
 * </ul>
 *
 * @see linit.linit.LinitPackage#getlistaCondicional()
 * @model
 * @generated
 */
public interface listaCondicional extends EObject
{
  /**
   * Returns the value of the '<em><b>I</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>I</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>I</em>' containment reference.
   * @see #setI(instrucciones)
   * @see linit.linit.LinitPackage#getlistaCondicional_I()
   * @model containment="true"
   * @generated
   */
  instrucciones getI();

  /**
   * Sets the value of the '{@link linit.linit.listaCondicional#getI <em>I</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>I</em>' containment reference.
   * @see #getI()
   * @generated
   */
  void setI(instrucciones value);

  /**
   * Returns the value of the '<em><b>L</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>L</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>L</em>' containment reference.
   * @see #setL(listaCondicional)
   * @see linit.linit.LinitPackage#getlistaCondicional_L()
   * @model containment="true"
   * @generated
   */
  listaCondicional getL();

  /**
   * Sets the value of the '{@link linit.linit.listaCondicional#getL <em>L</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>L</em>' containment reference.
   * @see #getL()
   * @generated
   */
  void setL(listaCondicional value);

} // listaCondicional
