/*
 * generated by Xtext 2.12.0
 */
package linit.ide

import com.google.inject.Guice
import linit.LinitRuntimeModule
import linit.LinitStandaloneSetup
import org.eclipse.xtext.util.Modules2

/**
 * Initialization support for running Xtext languages as language servers.
 */
class LinitIdeSetup extends LinitStandaloneSetup {

	override createInjector() {
		Guice.createInjector(Modules2.mixin(new LinitRuntimeModule, new LinitIdeModule))
	}
	
}
