/**
 * generated by Xtext 2.12.0
 */
package linit;

import linit.AbstractLinitRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class LinitRuntimeModule extends AbstractLinitRuntimeModule {
}
