/**
 * generated by Xtext 2.12.0
 */
package linit;

import linit.LinitStandaloneSetupGenerated;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class LinitStandaloneSetup extends LinitStandaloneSetupGenerated {
  public static void doSetup() {
    new LinitStandaloneSetup().createInjectorAndDoEMFRegistration();
  }
}
