/*
 * generated by Xtext 2.12.0
 */
package linit.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractLinitScopeProvider extends DelegatingScopeProvider {
}
