/**
 * generated by Xtext 2.12.0
 */
package linit.ide;

import linit.ide.AbstractLinitIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class LinitIdeModule extends AbstractLinitIdeModule {
}
