/**
 * generated by Xtext 2.12.0
 */
package linit.linit.util;

import linit.linit.*;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.util.Switch;

/**
 * <!-- begin-user-doc -->
 * The <b>Switch</b> for the model's inheritance hierarchy.
 * It supports the call {@link #doSwitch(EObject) doSwitch(object)}
 * to invoke the <code>caseXXX</code> method for each class of the model,
 * starting with the actual class of the object
 * and proceeding up the inheritance hierarchy
 * until a non-null result is returned,
 * which is the result of the switch.
 * <!-- end-user-doc -->
 * @see linit.linit.LinitPackage
 * @generated
 */
public class LinitSwitch<T> extends Switch<T>
{
  /**
   * The cached model package
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected static LinitPackage modelPackage;

  /**
   * Creates an instance of the switch.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public LinitSwitch()
  {
    if (modelPackage == null)
    {
      modelPackage = LinitPackage.eINSTANCE;
    }
  }

  /**
   * Checks whether this is a switch for the given package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param ePackage the package in question.
   * @return whether this is a switch for the given package.
   * @generated
   */
  @Override
  protected boolean isSwitchFor(EPackage ePackage)
  {
    return ePackage == modelPackage;
  }

  /**
   * Calls <code>caseXXX</code> for each class of the model until one returns a non null result; it yields that result.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the first non-null result returned by a <code>caseXXX</code> call.
   * @generated
   */
  @Override
  protected T doSwitch(int classifierID, EObject theEObject)
  {
    switch (classifierID)
    {
      case LinitPackage.PROGRAMA:
      {
        programa programa = (programa)theEObject;
        T result = caseprograma(programa);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LinitPackage.DECLARACIONES:
      {
        declaraciones declaraciones = (declaraciones)theEObject;
        T result = casedeclaraciones(declaraciones);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LinitPackage.INSTRUCCIONES:
      {
        instrucciones instrucciones = (instrucciones)theEObject;
        T result = caseinstrucciones(instrucciones);
        if (result == null) result = caseciclo(instrucciones);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LinitPackage.CONDICIONAL:
      {
        condicional condicional = (condicional)theEObject;
        T result = casecondicional(condicional);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LinitPackage.CICLO:
      {
        ciclo ciclo = (ciclo)theEObject;
        T result = caseciclo(ciclo);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      case LinitPackage.LISTA_CONDICIONAL:
      {
        listaCondicional listaCondicional = (listaCondicional)theEObject;
        T result = caselistaCondicional(listaCondicional);
        if (result == null) result = defaultCase(theEObject);
        return result;
      }
      default: return defaultCase(theEObject);
    }
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>programa</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>programa</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseprograma(programa object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>declaraciones</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>declaraciones</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casedeclaraciones(declaraciones object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>instrucciones</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>instrucciones</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseinstrucciones(instrucciones object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>condicional</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>condicional</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T casecondicional(condicional object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>ciclo</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>ciclo</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caseciclo(ciclo object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>lista Condicional</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>lista Condicional</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject) doSwitch(EObject)
   * @generated
   */
  public T caselistaCondicional(listaCondicional object)
  {
    return null;
  }

  /**
   * Returns the result of interpreting the object as an instance of '<em>EObject</em>'.
   * <!-- begin-user-doc -->
   * This implementation returns null;
   * returning a non-null result will terminate the switch, but this is the last case anyway.
   * <!-- end-user-doc -->
   * @param object the target of the switch.
   * @return the result of interpreting the object as an instance of '<em>EObject</em>'.
   * @see #doSwitch(org.eclipse.emf.ecore.EObject)
   * @generated
   */
  @Override
  public T defaultCase(EObject object)
  {
    return null;
  }

} //LinitSwitch
