/**
 * generated by Xtext 2.12.0
 */
package linit.ui;

import linit.ui.AbstractLinitUiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class LinitUiModule extends AbstractLinitUiModule {
  public LinitUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
