/**
 * generated by Xtext 2.12.0
 */
package linit.ui.contentassist;

import linit.ui.contentassist.AbstractLinitProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class LinitProposalProvider extends AbstractLinitProposalProvider {
}
