/*
 * generated by Xtext 2.12.0
 */
package linit.ui;

import com.google.inject.Injector;
import linit.ui.internal.LinitActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class LinitExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return LinitActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return LinitActivator.getInstance().getInjector(LinitActivator.LINIT_LINIT);
	}
	
}
