/**
 * generated by Xtext 2.12.0
 */
package linit.linit.impl;

import linit.linit.LinitPackage;
import linit.linit.ciclo;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>ciclo</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class cicloImpl extends MinimalEObjectImpl.Container implements ciclo
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected cicloImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return LinitPackage.Literals.CICLO;
  }

} //cicloImpl
