/*
 * generated by Xtext 2.12.0
 */
package linit.ui.tests;

import com.google.inject.Injector;
import linit.ui.internal.LinitActivator;
import org.eclipse.xtext.testing.IInjectorProvider;

public class LinitUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return LinitActivator.getInstance().getInjector("linit.Linit");
	}

}
