/*
 * generated by Xtext 2.12.0
 */
package linit.parser.antlr;

import com.google.inject.Inject;
import linit.parser.antlr.internal.InternalLinitParser;
import linit.services.LinitGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class LinitParser extends AbstractAntlrParser {

	@Inject
	private LinitGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_LINE_COMMENT");
	}
	

	@Override
	protected InternalLinitParser createParser(XtextTokenStream stream) {
		return new InternalLinitParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "programa";
	}

	public LinitGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(LinitGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
